stages:
  - name: "Build"
    jobs:
      - name: "Compile"
        script:
          - "compile_code.sh"
      - name: "Unit Test"
        script:
          - "run_unit_tests.sh"

  - name: "Deploy"
    jobs:
      - name: "Package"
        script:
          - "package_artifacts.sh"
      - name: "Deploy to Test Environment"
        script:
          - "deploy_to_test.sh"
      - name: "Integration Test"
        script:
          - "run_integration_tests.sh"

  - name: "Release"
    jobs:
      - name: "Deploy to Production"
        script:
          - "deploy_to_production.sh"
      - name: "Smoke Test"
        script:
          - "run_smoke_tests.sh"
